/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MapIterator */

#ifndef _Included_MapIterator
#define _Included_MapIterator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MapIterator
 * Method:    nativeIterateMap
 * Signature: (Ljava/util/Map;)V
 */
JNIEXPORT void JNICALL Java_MapIterator_nativeIterateMap
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
